/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Selector;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author apedroza
 */
public class MenuInterface extends javax.swing.JFrame {
    private String results = "";

    /**
     * Creates new form MenuInterface
     */
    public MenuInterface() {
        initComponents();
    }
    
    private void checkResults()
    {
        if(coughCheckBox3.isSelected())
        {
            results += "Dry-Cough";
        }
        results += "Generated";
    }
    
    //Creates the Text File named outputCommandFile
    private void outputCommandFile() {
        try {
            FileWriter writer = new FileWriter("outputCommandFile.txt", true);
            writer.append(results);
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(MenuInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introLabel = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        ageComboBox = new javax.swing.JComboBox<>();
        ageLabel = new javax.swing.JLabel();
        conditionLabel = new javax.swing.JLabel();
        kidneyCheckBox = new javax.swing.JCheckBox();
        lungCheckBox1 = new javax.swing.JCheckBox();
        ObesityCheckBox2 = new javax.swing.JCheckBox();
        immunoCheckBox3 = new javax.swing.JCheckBox();
        heartCheckBox4 = new javax.swing.JCheckBox();
        symptomsLabel = new javax.swing.JLabel();
        feverCheckBox1 = new javax.swing.JCheckBox();
        throatCheckBox5 = new javax.swing.JCheckBox();
        breathingCheckBox4 = new javax.swing.JCheckBox();
        coughCheckBox3 = new javax.swing.JCheckBox();
        tierdCheckBox = new javax.swing.JCheckBox();
        painsCheckBox6 = new javax.swing.JCheckBox();
        congestionCheckBox7 = new javax.swing.JCheckBox();
        diarrheaCheckBox8 = new javax.swing.JCheckBox();
        runnyCheckBox9 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COVID Information Generator");
        setAlwaysOnTop(true);
        setName("MenuFrame"); // NOI18N
        setResizable(false);

        introLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        introLabel.setText("Please select the information that applies to you. When you are done click Generate Commands");

        generateButton.setText("Generate Commands");
        generateButton.setActionCommand("generateButton");
        generateButton.setBorderPainted(false);
        generateButton.setFocusPainted(false);
        generateButton.setFocusable(false);
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        ageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age 0-9", "Age 10-19", "Age 20-24", "Age 25-59", "Age 60+" }));
        ageComboBox.setFocusable(false);

        ageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ageLabel.setText("- Select Your Age Range -");

        conditionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conditionLabel.setText("- PreExisting Conditions -");

        kidneyCheckBox.setText("Kidney Disease");
        kidneyCheckBox.setFocusPainted(false);
        kidneyCheckBox.setFocusable(false);

        lungCheckBox1.setText("Lung Disease");
        lungCheckBox1.setFocusPainted(false);
        lungCheckBox1.setFocusable(false);

        ObesityCheckBox2.setText("Obesitiy");
        ObesityCheckBox2.setFocusPainted(false);
        ObesityCheckBox2.setFocusable(false);

        immunoCheckBox3.setText("ImmunoCompromised");
        immunoCheckBox3.setFocusPainted(false);
        immunoCheckBox3.setFocusable(false);

        heartCheckBox4.setText("Heart Condition");
        heartCheckBox4.setToolTipText("");
        heartCheckBox4.setFocusPainted(false);
        heartCheckBox4.setFocusable(false);

        symptomsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        symptomsLabel.setText("- Current COVID Symptoms -");

        feverCheckBox1.setText("Fever");
        feverCheckBox1.setFocusPainted(false);
        feverCheckBox1.setFocusable(false);

        throatCheckBox5.setText("Sore-Throat");
        throatCheckBox5.setToolTipText("");
        throatCheckBox5.setFocusPainted(false);
        throatCheckBox5.setFocusable(false);

        breathingCheckBox4.setText("Difficulty Breathing");
        breathingCheckBox4.setFocusPainted(false);
        breathingCheckBox4.setFocusable(false);

        coughCheckBox3.setText("Dry-Cough");
        coughCheckBox3.setFocusPainted(false);
        coughCheckBox3.setFocusable(false);

        tierdCheckBox.setText("Tierdness");
        tierdCheckBox.setFocusPainted(false);
        tierdCheckBox.setFocusable(false);

        painsCheckBox6.setText("Pains");
        painsCheckBox6.setToolTipText("");
        painsCheckBox6.setFocusPainted(false);
        painsCheckBox6.setFocusable(false);

        congestionCheckBox7.setText("Nasal Congestion");
        congestionCheckBox7.setToolTipText("");
        congestionCheckBox7.setFocusPainted(false);
        congestionCheckBox7.setFocusable(false);

        diarrheaCheckBox8.setText("Diarrhea");
        diarrheaCheckBox8.setToolTipText("");
        diarrheaCheckBox8.setFocusPainted(false);
        diarrheaCheckBox8.setFocusable(false);

        runnyCheckBox9.setText("Runny-Nose");
        runnyCheckBox9.setToolTipText("");
        runnyCheckBox9.setFocusPainted(false);
        runnyCheckBox9.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breathingCheckBox4)
                            .addComponent(throatCheckBox5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(symptomsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(feverCheckBox1)
                                    .addComponent(tierdCheckBox)
                                    .addComponent(coughCheckBox3))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(painsCheckBox6)
                                    .addComponent(runnyCheckBox9)
                                    .addComponent(diarrheaCheckBox8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conditionLabel)
                            .addComponent(kidneyCheckBox)
                            .addComponent(lungCheckBox1)
                            .addComponent(ObesityCheckBox2)
                            .addComponent(immunoCheckBox3)
                            .addComponent(heartCheckBox4))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(ageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(congestionCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(introLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(introLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLabel)
                            .addComponent(conditionLabel)
                            .addComponent(symptomsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kidneyCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lungCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ObesityCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(immunoCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heartCheckBox4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feverCheckBox1)
                            .addComponent(diarrheaCheckBox8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tierdCheckBox)
                            .addComponent(runnyCheckBox9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coughCheckBox3)
                            .addComponent(painsCheckBox6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(breathingCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(throatCheckBox5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(congestionCheckBox7)
                    .addComponent(generateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        checkResults();//Generate code from the selected results
        outputCommandFile(); //Generates a txt file from Results.
        dispose(); //Close the Program
    }//GEN-LAST:event_generateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ObesityCheckBox2;
    private javax.swing.JComboBox<String> ageComboBox;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JCheckBox breathingCheckBox4;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JCheckBox congestionCheckBox7;
    private javax.swing.JCheckBox coughCheckBox3;
    private javax.swing.JCheckBox diarrheaCheckBox8;
    private javax.swing.JCheckBox feverCheckBox1;
    private javax.swing.JButton generateButton;
    private javax.swing.JCheckBox heartCheckBox4;
    private javax.swing.JCheckBox immunoCheckBox3;
    private javax.swing.JLabel introLabel;
    private javax.swing.JCheckBox kidneyCheckBox;
    private javax.swing.JCheckBox lungCheckBox1;
    private javax.swing.JCheckBox painsCheckBox6;
    private javax.swing.JCheckBox runnyCheckBox9;
    private javax.swing.JLabel symptomsLabel;
    private javax.swing.JCheckBox throatCheckBox5;
    private javax.swing.JCheckBox tierdCheckBox;
    // End of variables declaration//GEN-END:variables

}
